### ISSUE TITLE
Fix audit log receiver: cannot parse logs without objectRef

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher-sandbox/ob-team-opentelemetry-poc#1]
some metadata logs do not relate to kubernets objects, so the following policy:
```yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log all other requests at the Metadata level
  - level: Metadata
```
will not collect all logs.

We need to change the current `audit.tmpl.yaml` to support that usecase.
