### ISSUE TITLE
Investigate managed CRDs for platform engineers

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher-sandbox/ob-team-opentelemetry-poc#4]
Investigate what type of opinionated CRDs we want to provide for end users to consume, along the lines of:

```yaml
apiVersion: otel.stack.io
kind: PodFilter
spec:
   namespaceFilterRe : "^test"
   nameFilterRe : "[Az]+"
```

```yaml
apiVersion: otel.stack.io
kind: PodCollection
spec:
   namespaceFilterRe : "^test"
   nameFilterRe : "[Az]+"
```

That get built into open telemetry configurations for ease of use
